import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css"; 
import {Navbar} from'./navbar/nav'
import SessionProvider from "./SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Fuel Savy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body> 
        <SessionProvider>
          <Navbar />
          {children} 
        </SessionProvider>
      </body>
    </html>
  );
}
